FROM archlinux:base-devel

ARG UID=1000
ARG GID=1000

RUN groupadd -g $GID -o builder && \
    useradd -m -u $UID -g $GID -o -s /bin/bash builder && \
    echo "builder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builder && \
    chmod 0440 /etc/sudoers.d/builder

RUN pacman -Syu --noconfirm initramfs

USER builder

WORKDIR /workspace

ENTRYPOINT [ "env" ]